
    <div class="row">
        <!--<div class="col-md-2"></div>------>
        <!--<div class="col-md-8">-->
            <div class="jumbotron" style="background-color: #54E80C;">
                <!--<ul class="nav nav-pills justify-content-end">
                    <li class="nav-item">
                    <a class="nav-link btn btn-outline-dark" href="../index.php"> Início </a>
                    </li>
                </ul>-->
                <h1 class="display-4"> Operações com CPF </h1>
                <hr class="my-4">
                <p class="lead"> Escolha uma opção </p><br>
                <div class="row">
                    <div class="col">
                        <a href="validador.php" class="btn btn-dark color"> Validador de CPF </a>
                    </div>
                    <div class="col">
                        <a href="preenchedor.php" class="btn btn-dark color"> Preenchedor de CPF </a>
                    </div>
                    <div class="col">
                        <a href="gerador.php" class="btn btn-dark color"> Gerador de CPF </a>
                    </div>
                </div>
            </div>
        <!--</div>-->
        <!--<div class="col-md-2"></div>------>
    </div>
