<div class="row">
    <div class="col">
        <a href="/validador_de_cpf" class="btn btn-dark color flex-sm-fill text-sm-center"> Gerador / Validador de CPF </a>&nbsp;
    </div>
    <div class="col">
        <a href="gerador_de_senha/index.php" class="btn btn-dark color"> Gerador de senha </a>&nbsp;
    </div>
</div>
<br>
<div class="row">
    <div class="col">
        <a href="gerador_get_set/index.php" class="btn btn-dark color"> Gerador de Get e Set </a>&nbsp;
    </div>
    <div class="col">
        <a href="funcoes_data_e_hora/index.php" class="btn btn-dark color"> Manipular data e hora </a>&nbsp;
    </div>
</div>
<br>
<div class="row">
    <div class="col">
        <a href="https://color.adobe.com/pt/create/color-wheel" class="btn btn-dark color" target="_blank"> Adobe Color </a>&nbsp;
    </div>
    <div class="col">
        <a href="https://fontawesome.com/" class="btn btn-dark color" target="_blank"> Font Awesome </a>&nbsp;
    </div>
</div>
<br>
<div class="row">
    <div class="col">
        <a href="https://getbootstrap.com/" class="btn btn-dark color" target="_blank"> Bootstrap </a>&nbsp;
    </div>
    <div class="col">
        <a href="https://fonts.google.com/" class="btn btn-dark color" target="_blank"> Google Fonts </a>&nbsp;
    </div>
</div>
<br>
<div class="row">
    <div class="col">
        <a href="op_math/index.php" class="btn btn-dark color"> Operações matemáticas </a>&nbsp;
    </div>
    <!--<div class="col">
        <a href="#" class="btn btn-dark color"> Calculadora (em breve) </a>&nbsp;
    </div>-->
</div>