<!DOCTYPE html>
<html>
<head>
	<!--Css p/ Bootstrap -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="style.css">
	<title> Kit desenvolvimento </title>
</head>
<body>
    <div class="container">
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md-9">
                    <div class="jumbotron" style="background-color: #5282C4;">
                        <h1 class="display-4"> Kit desenvolvimento </h1>
                        <p class="lead"> Ferramentas básicas para desenvolver sistemas </p>
                        <hr class="my-4"><br>
                        <div class="container">